# Pull base image from Docker Hub
FROM node:16.14.2-alpine

# Set the working directory
WORKDIR /usr/app

# Copy the package.json file
COPY ./package*.json ./

# Install dependencies
RUN npm install

# Copy code from host to container
COPY . .

# Expose port 5173
EXPOSE 5173

# Run the app
CMD ["npm", "run", "dev"]